name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Verify lockfile
        run: |
          echo "Checking for lockfiles..."
          ls -la pnpm-lock.yaml || echo "Root lockfile not found"
          ls -la client/pnpm-lock.yaml || echo "Client lockfile not found"
          ls -la server/pnpm-lock.yaml || echo "Server lockfile not found"

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          pnpm config set store-dir ~/.pnpm-store

          # Install root dependencies first
          echo "Installing root dependencies..."
          pnpm install --frozen-lockfile --no-optional || {
            echo "Frozen lockfile failed, trying without frozen lockfile..."
            pnpm install --no-optional
          }

          # Verify installations
          echo "Verifying installations..."
          ls -la node_modules || echo "Root node_modules not found"
          ls -la client/node_modules || echo "Client node_modules not found"
          ls -la server/node_modules || echo "Server node_modules not found"

          # Check if vue-tsc is available
          echo "Checking vue-tsc availability..."
          cd client && npx vue-tsc --version || echo "vue-tsc not found in client"
          cd ../server && npx tsc --version || echo "tsc not found in server"

      - name: Run Type Check
        run: pnpm typecheck

      - name: Run Lint
        run: pnpm lint

      - name: Run Unit Tests
        run: pnpm test:unit

      - name: Run Build
        run: pnpm build

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ci-logs
          path: |
            client/dist/
            server/dist/
          retention-days: 7
