name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  actions: read

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile || pnpm install --no-frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Verify build output
        run: |
          echo "Checking build output..."
          ls -la client/dist/ || echo "Client dist not found"
          ls -la client/dist/index.html || echo "index.html not found"

      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          enablement: true
        continue-on-error: true

      - name: Check Pages Setup
        run: |
          echo "Checking if Pages is properly configured..."
          echo "If you see 'Resource not accessible by integration', please:"
          echo "1. Go to Settings > Pages and enable GitHub Actions as source"
          echo "2. Go to Settings > Actions > General and enable 'Read and write permissions'"
          echo "3. Re-run this workflow"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./client/dist"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: success()
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        continue-on-error: true

      - name: Check Deployment Status
        run: |
          echo "Deployment completed with status: ${{ steps.deployment.outcome }}"
          if [ "${{ steps.deployment.outcome }}" != "success" ]; then
            echo "Deployment failed. Please check the following:"
            echo "1. GitHub Pages is enabled in repository settings"
            echo "2. Source is set to 'GitHub Actions'"
            echo "3. Repository has 'Read and write permissions' enabled"
            echo "4. Repository is public (required for free GitHub Pages)"
          else
            echo "Deployment successful! Your site should be available shortly."
          fi
